version: 39
jobs:
- name: Send changes to GitHub
  steps:
  - !PushRepository
    name: push - OneDev to GitHub
    remoteUrl: https://github.com/jtdorseyiii/website
    userName: jtdorseyiii
    passwordSecret: OneDev to GitHub
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  - !TagCreateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: pull from GitHub to OneDev
  steps:
  - !PullRepository
    name: pull - GitHub to OneDev
    remoteUrl: https://github.com/jtdorseyiii/website
    userName: jtdorseyiii
    passwordSecret: OneDev to GitHub
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 0 1 * * ?
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
